db.ingredients.insert({name: "mozzarella", description: "fresh mozzarella is delicious on our pizza", quantity:"81"})
db.ingredients.insert({name: "parmesean", description: "fresh parmesean is delicious on our pizza", quantity:"74"})
db.ingredients.insert({name: "ricota", description: "fresh ricota is delicious on our pizza", quantity:"34"})
db.ingredients.insert({name: "gorgonzola", description: "fresh gorgonzola is delicious on our pizza", quantity:"132"})
db.ingredients.insert({name: "flour", description: "fresh flour is delicious on our pizza", quantity:"104"})
db.ingredients.insert({name: "salt", description: "fresh salt is delicious on our pizza", quantity:"82"})
db.ingredients.insert({name: "olive oil", description: "fresh olive oil is delicious on our pizza", quantity:"31"})
db.ingredients.insert({name: "mushrooms", description: "fresh mushrooms is delicious on our pizza", quantity:"96"})
db.ingredients.insert({name: "bell peppers", description: "fresh bell peppers is delicious on our pizza", quantity:"134"})
db.ingredients.insert({name: "banana peppers", description: "fresh banana peppers is delicious on our pizza", quantity:"71"})
db.ingredients.insert({name: "spinach", description: "fresh spinach is delicious on our pizza", quantity:"112"})
db.ingredients.insert({name: "Alfalfa Sprouts", description: "fresh Alfalfa Sprouts is delicious on our pizza", quantity:"102"})
db.ingredients.insert({name: "Artichoke hearts", description: "fresh Artichoke hearts is delicious on our pizza", quantity:"63"})
db.ingredients.insert({name: "Avocado  Baby leeks", description: "fresh Avocado  Baby leeks is delicious on our pizza", quantity:"125"})
db.ingredients.insert({name: "Beetroot", description: "fresh Beetroot is delicious on our pizza", quantity:"69"})
db.ingredients.insert({name: "Black Beans", description: "fresh Black Beans is delicious on our pizza", quantity:"73"})
db.ingredients.insert({name: "Broccoli", description: "fresh Broccoli is delicious on our pizza", quantity:"133"})
db.ingredients.insert({name: "Capers", description: "fresh Capers is delicious on our pizza", quantity:"139"})
db.ingredients.insert({name: "Capicolla", description: "fresh Capicolla is delicious on our pizza", quantity:"84"})
db.ingredients.insert({name: "Carrot", description: "fresh Carrot is delicious on our pizza", quantity:"95"})
db.ingredients.insert({name: "Cherry tomatoes", description: "fresh Cherry tomatoes is delicious on our pizza", quantity:"149"})
db.ingredients.insert({name: "Dried tomatoes", description: "fresh Dried tomatoes is delicious on our pizza", quantity:"149"})
db.ingredients.insert({name: "Eggplant", description: "fresh Eggplant is delicious on our pizza", quantity:"82"})
db.ingredients.insert({name: "Fungi", description: "fresh Fungi is delicious on our pizza", quantity:"72"})
db.ingredients.insert({name: "Fungi carciofi", description: "fresh Fungi carciofi is delicious on our pizza", quantity:"72"})
db.ingredients.insert({name: "Green peppers", description: "fresh Green peppers is delicious on our pizza", quantity:"51"})
db.ingredients.insert({name: "Kalamata olives", description: "fresh Kalamata olives is delicious on our pizza", quantity:"148"})
db.ingredients.insert({name: "Lettuce", description: "fresh Lettuce is delicious on our pizza", quantity:"112"})
db.ingredients.insert({name: "Mushrooms", description: "fresh Mushrooms is delicious on our pizza", quantity:"140"})
db.ingredients.insert({name: "Onions", description: "fresh Onions is delicious on our pizza", quantity:"45"})
db.ingredients.insert({name: "Olives", description: "fresh Olives is delicious on our pizza", quantity:"57"})
db.ingredients.insert({name: "Peas", description: "fresh Peas is delicious on our pizza", quantity:"49"})
db.ingredients.insert({name: "Porcini mushrooms", description: "fresh Porcini mushrooms is delicious on our pizza", quantity:"47"})
db.ingredients.insert({name: "Portobello Mushrooms", description: "fresh Portobello Mushrooms is delicious on our pizza", quantity:"119"})
db.ingredients.insert({name: "Red beans", description: "fresh Red beans is delicious on our pizza", quantity:"109"})
db.ingredients.insert({name: "Red onions", description: "fresh Red onions is delicious on our pizza", quantity:"72"})
db.ingredients.insert({name: "Red peppers", description: "fresh Red peppers is delicious on our pizza", quantity:"84"})
db.ingredients.insert({name: "Roast cauliflower", description: "fresh Roast cauliflower is delicious on our pizza", quantity:"21"})
db.ingredients.insert({name: "Roasted eggplant", description: "fresh Roasted eggplant is delicious on our pizza", quantity:"33"})
db.ingredients.insert({name: "Roasted Garlic", description: "fresh Roasted Garlic is delicious on our pizza", quantity:"18"})
db.ingredients.insert({name: "Roasted peppers", description: "fresh Roasted peppers is delicious on our pizza", quantity:"37"})
db.ingredients.insert({name: "scallions", description: "fresh scallions is delicious on our pizza", quantity:"111"})
db.ingredients.insert({name: "Shallots", description: "fresh Shallots is delicious on our pizza", quantity:"55"})
db.ingredients.insert({name: "Snow peas", description: "fresh Snow peas is delicious on our pizza", quantity:"148"})
db.ingredients.insert({name: "Spinach", description: "fresh Spinach is delicious on our pizza", quantity:"83"})
db.ingredients.insert({name: "Sun dried tomatoes", description: "fresh Sun dried tomatoes is delicious on our pizza", quantity:"41"})
db.ingredients.insert({name: "Sweet corn", description: "fresh Sweet corn is delicious on our pizza", quantity:"121"})
db.ingredients.insert({name: "Watercress", description: "fresh Watercress is delicious on our pizza", quantity:"122"})
db.ingredients.insert({name: "Wild mushrooms", description: "fresh Wild mushrooms is delicious on our pizza", quantity:"39"})
db.ingredients.insert({name: "Yellow peppers", description: "fresh Yellow peppers is delicious on our pizza", quantity:"117"})
db.ingredients.insert({name: "Yellow squash", description: "fresh Yellow squash is delicious on our pizza", quantity:"138"})
db.ingredients.insert({name: "Zucchini", description: "fresh Zucchini is delicious on our pizza", quantity:"79"})
db.ingredients.insert({name: "Bacon", description: "fresh Bacon is delicious on our pizza", quantity:"106"})
db.ingredients.insert({name: "meatballs", description: "fresh meatballs is delicious on our pizza", quantity:"134"})
db.ingredients.insert({name: "chicken", description: "fresh chicken is delicious on our pizza", quantity:"107"})
db.ingredients.insert({name: "peperoni", description: "fresh peperoni is delicious on our pizza", quantity:"77"})
db.ingredients.insert({name: "ham", description: "fresh ham is delicious on our pizza", quantity:"35"})
db.ingredients.insert({name: "sausage", description: "fresh sausage is delicious on our pizza", quantity:"82"})
