version: '2'
volumes:
  nosql-mongodata:
  nosql-nodemodules:
services:
  nosql-node:
    build: .
    image: "nosql-node"
    container_name: "nosql-node"
    environment:
      - NODE_ENV=development
    volumes:
      - ../../project1:/app/mongodb/project1
      - ../../labs:/app/mongodb/labs
      - ./examples:/app/mongodb/examples
      - ./lectures:/app/mongodb/lectures
      - nosql-nodemodules:/app/mongodb/node/node_modules
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 9000:9000
    links:
      - nosql-mongodb
    depends_on:
      - nosql-mongodb
  nosql-mongodb:
    image: mongo:latest
    container_name: "nosql-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - nosql-mongodata:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles
